
package Main;

import ActiveEntity.AECashier;
import ActiveEntity.AECustomer;
import ActiveEntity.AEManager;
import SACashier.ICashier_Cashier;
import SACashier.ICashier_Customer;
import SACashier.SACashier;
import SACorridor.ICorridor_Customer;
import SACorridor.SACorridor;
import SACorridorHall.ICorridorHall_Customer;
import SACorridorHall.SACorridorHall;
import SACustomer.SACustomer;
import SAOutsideHall.IOutsideHall_Customer;
import SAOutsideHall.SAOutsideHall;
import SACustomer.ICustomer_Customer;
import SAEntranceHall.IEntranceHall_Customer;
import SAEntranceHall.IEntranceHall_Manager;
import SAEntranceHall.SAEntranceHall;
import SAManager.IManager_Customer;
import SAManager.IManager_Manager;
import SAManager.SAManager;
import SAOutsideHall.IOutsideHall_Manager;
import SAPaymentBox.IPaymentBox_Cashier;
import SAPaymentBox.IPaymentBox_Customer;
import SAPaymentBox.SAPaymentBox;
import SAPaymentHall.IPaymentHall_Cashier;
import SAPaymentHall.IPaymentHall_Customer;
import SAPaymentHall.SAPaymentHall;

/*
 * @author Rafael Sá (104552), Luís Laranjeira (81526)
 */
public class OIS extends javax.swing.JFrame {

    private final int MAX_CUSTOMERS = 99;
    private final int N_CORRIDOR = 3;
    private final int SIZE_ENTRANCE_HALL = 6;
    private final int SIZE_CORRIDOR_HALL = 3;
    private final int SIZE_CORRIDOR = 2;
    private final int SIZE_PAYMENT_HALL = 3;

    /**
     * Creates new form OIS
     */
    public OIS() {
        initComponents();
        initOIS();
    }

    private void initOIS() {

        final SACustomer saCustomer = new SACustomer(MAX_CUSTOMERS);
        final SAManager saManager = new SAManager();
        final SACashier saCashier = new SACashier();
        final SAOutsideHall saOutsideHall = new SAOutsideHall(MAX_CUSTOMERS);
        final SAEntranceHall saEntranceHall = new SAEntranceHall(SIZE_ENTRANCE_HALL);
        final SACorridorHall[] saCorridorHall = new SACorridorHall[N_CORRIDOR];
        final SACorridor[] saCorridor = new SACorridor[N_CORRIDOR];
        for (int i = 0; i < N_CORRIDOR; i++) {
            saCorridorHall[i] = new SACorridorHall(SIZE_CORRIDOR_HALL);
            saCorridor[i] = new SACorridor(SIZE_CORRIDOR);
        }
        final SAPaymentHall saPaymentHall = new SAPaymentHall(SIZE_PAYMENT_HALL);
        final SAPaymentBox sAPaymentBox = new SAPaymentBox();

        final AEManager aeManager = new AEManager((IManager_Manager) saManager, (IOutsideHall_Manager) saOutsideHall,
                                                   (IEntranceHall_Manager) saEntranceHall);
        aeManager.start();
        final AECashier aeCashier = new AECashier((IPaymentHall_Cashier) saPaymentHall, 
                                        (IPaymentBox_Cashier) sAPaymentBox, (ICashier_Cashier) saCashier);
        aeCashier.start();
        final AECustomer[] aeCustomer = new AECustomer[MAX_CUSTOMERS];
        for (int i = 0; i < MAX_CUSTOMERS; i++) {
            aeCustomer[i] = new AECustomer(i, (ICustomer_Customer) saCustomer,
                    (IOutsideHall_Customer) saOutsideHall, (IEntranceHall_Customer) saEntranceHall,
                    (ICorridorHall_Customer[]) saCorridorHall, (ICorridor_Customer[]) saCorridor,
                    (IPaymentHall_Customer) saPaymentHall, (IPaymentBox_Customer) sAPaymentBox,
                    (ICashier_Customer) saCashier, (IManager_Customer) saManager);
            aeCustomer[i].start();
        }

        try {
            aeManager.join();
            aeCashier.join();
            for (int i = 0; i < MAX_CUSTOMERS; i++) {
                aeCustomer[i].join();
            }
        } catch (Exception ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OIS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
